module.exports = {
  1: {
    required: [
      "bedrooms",
      "bathrooms",
      "level",
      "payment_method",
      "down_payment",
      "installment_years",
      "ready_to_move",
      "furnished",
    ],
    allowed: [
      "area_m2",
      "am_seeview",
      "am_pool",
      "am_balcony",
      "am_private_garden",
      "am_kitchen",
      "am_ac",
      "am_heating",
      "am_elevator",
      "am_gym",
    ],
  },
  2: {
    required: [
      "deposit_amount",
      "bedrooms",
      "bathrooms",
      "level",
      "rent_frequency",
      "adult_no_max",
    ],
    allowed: [
      "child_no_max",
      "min_rent_period",
      "min_rent_period_unit",
      "available_from",
      "available_to",
      "area_m2",
      "am_seeview",
      "am_pool",
      "am_balcony",
      "am_private_garden",
      "am_kitchen",
      "am_ac",
      "am_heating",
      "am_elevator",
      "am_gym",
    ],
  },
};
